import 'package:flutter/material.dart';
import 'package:nfc_manager/nfc_manager.dart';
import 'package:google_fonts/google_fonts.dart';
import 'home_screen.dart';

class LinkTagScreen extends StatefulWidget {
  // We pass the secure token generated by your .NET backend to this screen
  final String digitalToken;
  final bool isRelinking;

  const LinkTagScreen({super.key, required this.digitalToken, this.isRelinking = false});

  @override
  State<LinkTagScreen> createState() => _LinkTagScreenState();
}

class _LinkTagScreenState extends State<LinkTagScreen> {
  bool _isScanning = false;
  String _statusMessage = 'Tap "Start Writing" and hold your tag near the back of your phone to link your identity.';

  @override
  void dispose() {
    // Always ensure the NFC session is closed when leaving the screen
    NfcManager.instance.stopSession();
    super.dispose();
  }

  Future<void> _startNfcWrite() async {
    // 1. Check if the phone actually has NFC and it is turned on
    bool isAvailable = await NfcManager.instance.isAvailable();
    if (!isAvailable) {
      setState(() {
        _statusMessage = 'NFC is not available or turned off on this device.';
      });
      return;
    }

    setState(() {
      _isScanning = true;
      _statusMessage = 'Looking for ZimPay Tag...';
    });

    // 2. Start the NFC Session
    NfcManager.instance.startSession(onDiscovered: (NfcTag tag) async {
      // 3. Try to read the tag as an NDEF formatted tag
      var ndef = Ndef.from(tag);

      if (ndef == null || !ndef.isWritable) {
        NfcManager.instance.stopSession(errorMessage: 'Tag is not NDEF formatted or not writable.');
        if (mounted) {
          setState(() {
            _isScanning = false;
            _statusMessage = 'Error: Tag is locked or not supported.';
          });
        }
        return;
      }

      // 4. Create the NDEF Message containing your backend Digital Token
      NdefMessage message = NdefMessage([
        NdefRecord.createText(widget.digitalToken),
      ]);

      try {
        // 5. Write to the tag!
        await ndef.write(message);

        NfcManager.instance.stopSession();

        if (mounted) {
          setState(() {
            _isScanning = false;
            _statusMessage = '✅ Success! Your physical tag is now securely linked to your ZimPay identity.';
          });

          if (!context.mounted) return;

          // Show the success notification
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(widget.isRelinking ? 'Tag Relinked Successfully!' : 'Registration Successful! Welcome to ZimPay.'),
              backgroundColor: Colors.green,
            ),
          );

          // Route to Home Screen
          Future.delayed(const Duration(seconds: 2), () {
            if (!mounted) return;
            if (widget.isRelinking) {
              Navigator.pop(context);
            } else {
              Navigator.pushAndRemoveUntil(
                context,
                MaterialPageRoute(builder: (context) => const HomeScreen()),
                (route) => false, // This clears the navigation stack
              );
            }
          });
        }
      } catch (e) {
        NfcManager.instance.stopSession(errorMessage: e.toString());
        if (mounted) {
          setState(() {
            _isScanning = false;
            _statusMessage = 'Failed to write to tag. Try holding it steadier.';
          });
        }
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF4F7FA),
      appBar: AppBar(
        title: Text('Link Identity Tag', style: GoogleFonts.plusJakartaSans(fontWeight: FontWeight.bold)),
        backgroundColor: Colors.transparent,
      ),
      body: Padding(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            // A pulsing or static icon depending on state
            Icon(
              _isScanning ? Icons.contactless : Icons.nfc,
              size: 100,
              color: _isScanning ? const Color(0xFF0058BA) : Colors.grey,
            ),
            const SizedBox(height: 32),
            Text(
              _statusMessage,
              textAlign: TextAlign.center,
              style: GoogleFonts.inter(fontSize: 16, color: const Color(0xFF2B2F32)),
            ),
            const SizedBox(height: 48),
            if (!_isScanning && _statusMessage.contains('Success'))
              SizedBox(
                width: double.infinity,
                child: ElevatedButton(
                  onPressed: () {
                    if (widget.isRelinking) {
                      Navigator.pop(context);
                    } else {
                      Navigator.pushAndRemoveUntil(
                        context,
                        MaterialPageRoute(builder: (context) => const HomeScreen()),
                        (route) => false,
                      );
                    }
                  },
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFF006A2B), // Success green
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(vertical: 16),
                  ),
                  child: Text(widget.isRelinking ? 'Done' : 'Go to Home', style: const TextStyle(fontSize: 16)),
                ),
              ),
            if (!_isScanning && !_statusMessage.contains('Success'))
              SizedBox(
                width: double.infinity,
                child: ElevatedButton(
                  onPressed: _startNfcWrite,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFF0058BA),
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(vertical: 16),
                  ),
                  child: const Text('Start Writing', style: TextStyle(fontSize: 16)),
                ),
              ),
          ],
        ),
      ),
    );
  }
}